### ISSUE TITLE
Provide react-live recommendation

### ISSUE THREAD

**Issue by kenwheeler** [FormidableLabs/component-playground#100]
It would be great to have a pros and cons, use cases section in the README for react-live vs component playground. This ticket can serve as a place to refine ideas about how to actually communicate that.

**Comment by philpl** [comment]
How I'd currently describe it is:

- component-playground uses babel-standalone, react-live uses bublé (I might make this customisable soon)
- component-playground has a larger bundle, but uses a more familiar editor setup, compared to react-live (custom editor around prism)
- react-live is more modular/customisable and has a smaller bundle size, component-playground is easier/faster to set up
- component-playground is not server-side renderable, react-live is
- component-playground might have more predictable error handling than react-live in some cases (due to react-dom, see above; this might change with React 16 though)

I think those are the main points for comparison, right?

**Comment by ryan-roemer** [comment]
@philpl @kenwheeler -- I've taken a first stab at a README section draft based on Phil's bullet points at https://gist.github.com/ryan-roemer/155b204a420ec78d8e275f7e3d6de1b3

Love to hear suggestions / edits / additions!

**Comment by philpl** [comment]
@ryan-roemer This looks great! 🌟 It should help everyone to make an informed decision and I think every consideration is covered 👍
