### ISSUE TITLE
BUG: Remove demo link to https://formidable.com/open-source/component-playground/

### ISSUE THREAD

**Issue by hackhat** [FormidableLabs/component-playground#134]

**Comment by JonathanLehner** [comment]
still doesn't work :(

**Comment by ryan-roemer** [comment]
Hi folks! We no longer maintain a separate demo, and instead just use this repository as the sole site for documentation. If someone has a moment, we'd ❤️ a PR to remove the demo link...

/cc @boygirl

**Comment by jzabroski** [comment]
Is there a reason to not host a separate demo?  Was the site being attacked or something?

**Comment by ryan-roemer** [comment]
IIRC it's because we have a **lot** of OSS "lander sites" as an extra introduction enhancement on top of the GitHub based docs and periodically review which need the extra lander boost...

@boygirl -- Do you know if there some demo out there for the playground aside from the former formidable.com site location?

**Comment by boygirl** [comment]
No, I do think there is a specific component playground demo, but formidable.com/open-source/victory still uses component-playground extensively

**Comment by boygirl** [comment]
Just removed the demo links
