### ISSUE TITLE
Deprecate noRender

### ISSUE THREAD

**Issue by baer** [FormidableLabs/component-playground#19]
The `noRender` prop should be deprecated in favor of wrapped components. This will allow greater flexibility in parent-child relationships and specifically with passing context into a component.

**Comment by jquense** [comment]
hmm this seems like an unnecessary move, why remove the option completely? I find the "component floating in the void" aspect of noRender really confusing, and error prone, and extremely limiting.

users working with the component in the editor _have no idea_ they can't add code outside the component, and will get very unhelpful errors when they do. It also means we cannot demonstrate _any_ logic, can't attach handlers, can't show state, etc. This decision really only works for simple display only or completely contained components.

**Comment by cef62** [comment]
I understand the benefits of using wrapped components but I don't grasp how to permit creation of new components from the editor without disabling `noRender`.
Can you explain it?

**Comment by IanVS** [comment]
So, I am trying to implement a higher order component similar to http://khan.github.io/react-components/#sortable.  How can I now do this without `noRender`?  I've been banging my head on a wall for a few hours trying to get this to work.  Maybe you could include an example of how to do this?

**Comment by kenwheeler** [comment]
Sorry @ianvs , will give this repo some love this week, been tied up getting our other repos released. Can you post an example of what you're trying to do?

**Comment by IanVS** [comment]
I haven't forgotten about this, just need to take the time to create a gist.  For now, I just get a bunch of deprecation warnings in the console from component-playground.  The link to the Kahn Academy component should pretty clearly show what I'm trying to do (i.e. show an example of using a higher-order-component).

**Comment by coopy** [comment]
https://github.com/FormidableLabs/component-playground/pull/49

**Comment by IanVS** [comment]
I'd rather it just wasn't deprecated at all.  I don't see the reason this functionality would need to be removed.

**Comment by baer** [comment]
Basically the reason it is deprecated is that this is not supposed to be a REPL or a code-example plugin - it was built for showcasing built components in something of a living style guide. For the times when you  do need to do something more than showcasing a built component, you can use `es6Preview`.

The two main problems are this:

1. `noRender === false` [turns the component playground into stunted REPL](https://github.com/FormidableLabs/component-playground/blob/master/src/components/preview.jsx#L60-L64). We already have `es6Preview` which means there are two code paths to accomplish mostly the same thing.
2. No support for context - This is the big one. By allowing the no-render to be false we lose the ability to control the root and therefore the ability to control context or any other thing like i18n or top level data. Using `noRender` causes inconsistent API behavior which is why it got deprecated.

@IanVS - Is there a reason you can't use the ES6Preview for what you want?

**Comment by IanVS** [comment]
I will try out es6Preview, thanks.  Is it the same thing as `es6Console`, mentioned in the readme and examples?  If so, it doesn't seem like quite what I need.  I am indeed showcasing built components in a living styleguide, except that some of my components will be higher-order components.  Using `console.log` to render the examples seems a bit clunky, since the example code I want to provide is essentially an example of how to implement the library's components, but I shouldn't judge it before I give it a try...

**Comment by alexlande** [comment]
Since 1.0 has been released and this isn't removed yet (which I'm grateful for), I wanted to come back and look at this again.

I agree that removing `noRender` without some way of providing functionally equivalent behavior would be a bummer. There are a lot of cases where the ability to provide a complete react component and render it in an example is helpful. The Khan Academy examples provided previously are a good example of a higher order component use case.

Unless I'm missing something, `es6Console` doesn't provide even remotely the same functionality as `noRender`. I wasn't able to render a component through a `console.log` with `es6Console`, and even if that was theoretically possible it wouldn't make any sense and would be pretty jarring and weird as documentation.

All that is to say that I feel strongly that this option shouldn't be removed without first providing another way to handle higher order components.

**Comment by chrisbolin** [comment]
@alexlande and @coopy - since i am merging #74, could we also officially table and close (for now) this issue? I'd really like to do is get rid of the scary README warning:
> *noRender - (Deprecated, Remove at 1.x)*

**Comment by chrisbolin** [comment]
I should note that Formidable uses `noRender` all over our docs. e.g. http://formidable.com/open-source/victory/docs/

**Comment by alexlande** [comment]
Yeah, definitely 👍
